export const glossaryTerms = [
  {
    id: 'mainframe',
    term: 'Mainframe',
    category: 'System View',
    definition: 'Mainframes are data servers designed to process up to 1 trillion web transactions daily with the highest levels of security and reliability.',
  },
  {
    id: 'cpc',
    term: 'CPC',
    category: 'Compute',
    definition: 'Central Processor Complex. The core processor complex inside the mainframe, not the entire mainframe system.',
  },
  {
    id: 'processor-complex',
    term: 'Processor Complex',
    category: 'Compute',
    definition: 'The compute section of the system, including processor capacity, accelerator capacity, and workload headroom.',
  },
  {
    id: 'lpar',
    term: 'LPAR',
    category: 'Virtualization',
    definition: 'Logical Partition. A hardware-isolated partition used to run separate operating environments on the same mainframe.',
  },
  {
    id: 'raim',
    term: 'RAIM',
    category: 'Memory',
    definition: 'Redundant Array of Independent Memory. A resilient memory design used to improve reliability and availability.',
  },
  {
    id: 'external-dasd',
    term: 'External DASD',
    category: 'External Storage',
    definition: 'Direct Access Storage Device represented here only as an optional external storage cabinet, not as a CPC module.',
  },
  {
    id: 'io-connectivity-drawers',
    term: 'I/O Connectivity Drawers',
    category: 'CPC I/O',
    definition: 'The CPC module for OSA, FICON, Fibre Channel, and high-throughput links. It provides connectivity, not DASD capacity.',
  },
  {
    id: 'ficon',
    term: 'FICON',
    category: 'I/O',
    definition: 'Fiber Connection. A high-speed IBM Z channel protocol commonly used to connect storage and tape systems.',
  },
  {
    id: 'fibre-channel',
    term: 'Fibre Channel',
    category: 'I/O',
    definition: 'A storage networking technology used in SAN environments for fast and reliable data transfer.',
  },
  {
    id: 'san',
    term: 'SAN',
    category: 'Storage',
    definition: 'Storage Area Network. A dedicated network that connects servers to shared storage systems.',
  },
  {
    id: 'osa',
    term: 'OSA',
    category: 'Network',
    definition: 'Open Systems Adapter. IBM Z networking hardware used for TCP/IP and Ethernet connectivity.',
  },
  {
    id: 'hmc',
    term: 'HMC',
    category: 'Management',
    definition: 'Hardware Management Console. A management interface used to configure, monitor, and operate IBM Z hardware.',
  },
  {
    id: 'support-element',
    term: 'Support Element',
    category: 'Management',
    definition: 'A service processor used for low-level hardware control, diagnostics, and platform operations.',
  },
  {
    id: 'io-fabric',
    term: 'I/O Fabric',
    category: 'I/O',
    definition: 'The connectivity layer that links the mainframe to external storage, network, tape, and recovery systems.',
  },
  {
    id: 'crypto-express',
    term: 'Crypto Express',
    category: 'Security',
    definition: 'A hardware cryptographic feature used for secure key handling, encryption, and compliance-focused workloads.',
  },
  {
    id: 'pervasive-encryption',
    term: 'Pervasive Encryption',
    category: 'Security',
    definition: 'An IBM Z approach for encrypting data broadly across applications, databases, and storage with reduced application changes.',
  },
  {
    id: 'quantum-safe-security',
    term: 'Quantum-safe security',
    category: 'Security',
    definition: 'Security planning and cryptography intended to reduce risk from future quantum-computing attacks.',
  },
  {
    id: 'tape',
    term: 'Tape',
    category: 'External Backup',
    definition: 'A removable-media backup and retention technology represented here through the optional external Tape Library module.',
  },
  {
    id: 'tape-library',
    term: 'Tape Library',
    category: 'External Backup',
    definition: 'The optional external automated tape system used for backup, long-term retention, and air-gapped recovery workflows.',
  },
  {
    id: 'cyber-vault',
    term: 'Cyber Vault',
    category: 'External Recovery',
    definition: 'An optional external recovery copy tier used to isolate critical data and support recovery after cyber incidents.',
  },
  {
    id: 'air-gapped-backup',
    term: 'Air-gapped backup',
    category: 'Backup',
    definition: 'A backup copy separated from normal network access so attackers cannot easily modify or delete it.',
  },
  {
    id: 'rear-door-heat-exchanger',
    term: 'Rear Door Heat Exchanger',
    category: 'Cooling',
    definition: 'A cooling attachment that removes heat at the rear of the frame before it enters the datacenter room.',
  },
  {
    id: 'liquid-cooling',
    term: 'Liquid Cooling',
    category: 'Cooling',
    definition: 'A cooling method that uses liquid to support higher density and higher performance hardware configurations.',
  },
  {
    id: 'frame',
    term: 'Frame',
    category: 'Infrastructure',
    definition: 'The physical cabinet layout that houses the mainframe hardware and supporting infrastructure.',
  },
  {
    id: 'z-frame',
    term: 'Z Frame',
    category: 'Infrastructure',
    definition: 'The primary mainframe frame used for core CPC, memory, I/O, security, power, and cooling modules.',
  },
  {
    id: 'a-frame',
    term: 'A Frame',
    category: 'Infrastructure',
    definition: 'An additional frame used when the selected configuration needs more infrastructure or external-system support.',
  },
  {
    id: 'capacity-score',
    term: 'Capacity score',
    category: 'Assessment',
    definition: 'A demo metric in this configurator that compares relative compute strength between selectable options.',
  },
  {
    id: 'ai-score',
    term: 'AI score',
    category: 'Assessment',
    definition: 'A demo metric that compares how AI-oriented a selected processor or security option is inside the configurator.',
  },
  {
    id: 'estimated-consumption',
    term: 'Estimated consumption',
    category: 'Assessment',
    definition: 'The approximate power draw calculated from the selected modules and cooling efficiency.',
  },
];
